### Varibales
@apiUrl = http://localhost:3011

### Menu
GET @{{apiUrl}}/api/v1/menu

### Events
GET @{{apiUrl}}/api/v1/events

### Specific Menu Item By Id
GET @{{apiUrl}}/api/v1/menu/:id

### Specific Event By Id
GET @{{apiUrl}}/api/v1/events/:id

### Add Menu Item
POST @{{apiUrl}}/api/v1/menu
Content-Type: application/json
{
    "Name": "Donut",
    "Description": "Fresh Glazed Donut",
    "Price": "1.99",
    "Url": "https://assets.epicurious.com/photos/54b0226d766062b20344580a/1:1/w_2560%2Cc_limit/51160200_glazed-doughnuts_1x1.jpg",
    
}

## Add Event
POST @{{apiUrl}}/api/v1/events
Content-Type: application/json
{
    "blah": "blah",
    "blah": "blah",
}

