### Menu
GET /api/v1/menu

### Events
GET /api/v1/events

### Specific Menu Item By Id
GET api/v1/menu/:id

### Specific Event By Id
GET /api/v1/events/:id

### Add Menu Item
POST /api/v1/menu

## Add Event
POST /api/v1/events